---
- name: Converge
  hosts: all
  roles:
    - role: "kreinhub.docker_compose_install"
    - role: "kreinhub.ingress_compose_up"
    - role: "kreinhub.flask-compose-up"
  # tasks:
  #   - name: "Include flask-compose-up"
  #     include_role:
  #       name: "kreinhub.flask_compose_up"
