---
- name: Converge
  hosts: all
  roles:
    - role: "docker-compose-install"
    - role: "ingress-compose-up"
  tasks:
    - name: "Include flask-compose-up"
      include_role:
        name: "flask-compose-up"
